### ISSUE TITLE
[Spike] @Async annotation in Spring 6 (Boot 3) is bypassing our existing CompletableFuture instrumentation

### ISSUE THREAD

**Issue by jtduffy** [newrelic/newrelic-java-agent#1741] opened 2024-02-14 19:31 UTC
### Description
In Spring 6, it seems that the `@Async` annotation is using the `CompletableFuture` API differently than previous versions which is causing our instrumentation not to work. The specific issue that drove the original support ticket was external calls not reporting to NR when they were wrapped in `CompletableFuture` instances.  A repro app is attached that exhibits this behavior.

### Acceptance Criteria
Our `CompletableFuture` module applies to Spring 6 apps using the `@Async` annotation.

[new-relic-agent-sb3-spring6-repro.zip](https://github.com/newrelic/newrelic-java-agent/files/14285240/new-relic-agent-sb3-spring6-repro.zip)

**Comment by meiao** [comment] 2024-02-15 22:01
Ideally this should be tested with Dynamic proxies and CGLIB beans.
Dynamic proxies are created when the service bean implements an interface.
CGLIB is used when it does not.

**Comment by kford-newrelic** [comment] 2024-02-16 00:50
Need to spike on this to better determine what's going on.

**Comment by kanderson250** [comment] 2024-05-02 20:00
Investigated and found the cause- Spring 6 now handles `@Async` annotations with a call to `CompletableFuture.completeAsync`. This is a method that was introduced to the CompletableFuture spec in Java 9, so it is not currently part of our Java 8+ CompletableFuture instrumentation. 

Verified that a quick POC instrumenting this method fixed the issue for both Dynamic Proxy and CGLIB. 

Closing this spike ticket and opening a story to add `completeAsync` to a new Java 9+ CompletableFuture instrumentation module.

**Closed by kanderson250** 2024-05-02 20:00 UTC
Labels: GTSE, 2, apr-jun qtr, spike
