### ISSUE TITLE
Add instrumentation for Reactive Relational Database Connectivity

### ISSUE THREAD

**Issue by markusgay** [newrelic/newrelic-java-agent#118] opened 2020-11-17 18:37 UTC
## Feature Description
In one of our latest projects, we use the reactive spring framework with the Reactive Relational Database Connectivity MySQL Implementation to access the MySQL database. With the lack of instrumentation, the NewRelic database operation page is blank. We are looking for generic instrumentation for r2dbc-spi (https://github.com/r2dbc/r2dbc-spi) in the near term. And in the longer term, instrumentation for r2dbc-mysql (https://github.com/mirromutth/r2dbc-mysql).

## Priority
Really Want

**Comment by tspring** [comment] 2020-11-18 15:29
Hi @markusgay  Thanks for letting us know. I've added this to the internal tool to used by our product manager to track feature requests; however, it's unlikely we'll get to this in the near future. That said, I suspect if you're using this in a [Spring Webflux](https://github.com/newrelic/newrelic-java-agent/blob/main/instrumentation/spring-webflux-5.1.0/src/main/java/org/springframework/web/reactive/DispatchHandler_Instrumentation.java#L23) application a lot of the reactive async Transaction linking work should be done in version 6.2.1 of the Java agent and a quick solution could probably be done using the [Datastore API](https://newrelic.github.io/java-agent-api/javadoc/com/newrelic/api/agent/DatastoreParameters.html) within your application. I'd also be happy to help in whatever way I can if you'd like to write an instrumentation module.

Also, while not necessary, if you could provide a simple example application it would be a great help to us. Thanks again, and let me know if you have any questions

**Comment by mp911de** [comment] 2020-11-28 18:57
FWIW, [R2DBC proxy](https://github.com/r2dbc/r2dbc-proxy) is built for the purpose of allowing 3rd party libraries to observe R2DBC activity.

**Comment by kford-newrelic** [comment] 2021-06-02 16:36
Duplicate of #167 and related specific drivers. Further development planned to start in July.

**Closed by kford-newrelic** 2021-06-02 16:36 UTC
Labels: enhancement, help wanted, track-interest
