### ISSUE TITLE
java.lang.NoSuchMethodError: com.nr.agent.instrumentation.cassandra.CassandraUtils.wrapSyncRequest

### ISSUE THREAD

**Issue by amar-kopric** [newrelic/newrelic-java-agent#1991] opened 2024-07-26 12:44 UTC
I recently upgraded my maven project from spring boot 2.1 to 2.7 in which I utilize the newrelic-api dependency for some custom metrics. After the upgrade my cassandra queries keep failing with the following error:

com.nr.agent.instrumentation.cassandra.CassandraUtils.wrapSyncRequest(Lcom/datastax/oss/driver/api/core/cql/Statement;Lcom/datastax/oss/driver/api/core/cql/ResultSet;Lcom/datastax/oss/driver/api/core/CqlIdentifier;Lcom/newrelic/api/agent/Segment;)Lcom/datastax/oss/driver/api/core/cql/ResultSet;]

Looking at the changelogs for both spring boot and newrelic, I found out that the datastax library has been upgraded to version 4.x with the spring boot upgrade and that the newrelic agent now has the support for the datastax version 4.x. 

Is the only solution to fixing this to include the newrelic-agent dependency along side the newrelic-api dependency? Since I can see that some projects have even newer version of spring boot and datastax and don't need to include the newrelic-agent dependency and their cassandra queries are working just fine.

**Comment by amar-kopric** [comment] 2024-08-09 13:55
To add to this, we have tried adding the newrelic-agent dependency in our project but the we did not resolve the issue. The only current workaround is to disable the datastax4 instrumentation in the newrelic.yml file like so:

  class_transformer:
    com.newrelic.instrumentation.cassandra-datastax-4.0.0:
      enabled: false
      
This help us keep our endpoints/services working but without instrumentation

**Comment by deleonenriqueta** [comment] 2024-08-09 21:19
@amar-kopric Thanks for the update!

Can you please provide me with the last working version of the driver as well as the version of the driver that results in failing Cassandra queries?

**Comment by deleonenriqueta** [comment] 2024-08-13 20:02
Hello @amar-kopric, with the information provided I've tried reproducing the `NoSuchMethodError` but queries are not failing on my end. I've tested querying Cassandra with multiple methods (query builder, explicit CQL statements, mapper). If you're able to provide me with the following information, I can continue to investigate the issue:

- Repro App
- A code snippet that includes how you are querying Cassandra
- Full Stack Trace of the Exception
- pom.xml

**Comment by deleonenriqueta** [comment] 2024-09-03 16:21
Marking this issue as `wontfix` and closing it out since we've had no reply for several weeks.

**Closed by deleonenriqueta** 2024-09-03 16:21 UTC
Labels: bug, wontfix, blocked
