### ISSUE TITLE
Fix "Illegal Reflective Access" warning

### ISSUE THREAD

**Issue by jeffalder** [newrelic/newrelic-java-agent#13] opened 2020-08-10 17:04 UTC
## Description
When the agent starts up on Java 9+ it logs the following warning messages:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.newrelic.weave.weavepackage.NewClassAppender (file:/deploy/newrelic.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.newrelic.weave.weavepackage.NewClassAppender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

We should either find a way to suppress these message, or better yet we should fix NewClassAppender such that it doesn't use this illegal access.

This is difficult because our utility classes are appended to the appropriate classloader that pulled in an instrumentation jar. We have to find a way to provide those classes to our classloader instrumentation so it can define the classes on that classloader when necessary.

## Expected Behavior
Agent works the same with no loss of features.
No Reflective Access Warning.
No problems when using "redeploys" like in tomcat.

## Your Environment
Java 9+

**Comment by brunobat** [comment] 2020-11-12 12:09
This affects us. This was reported over 1y now, here: https://discuss.newrelic.com/t/an-illegal-reflective-access-operation-has-occurred-with-java-agent-4-11-0/68195/20

**Comment by Silmoheru** [comment] 2021-02-08 03:47
has this been solved yet as im also getting this

**Comment by brunobat** [comment] 2021-03-15 10:48
Got the same error this week:
`WARNING:` Illegal reflective access by com.newrelic.weave.weavepackage.NewClassAppender (file:/app/lib/com.newrelic.agent.java.newrelic-agent-5.12.0.jar) to method java.net.URLClassLoader.addURL(java.net.URL)`
This caused a JVM failure and restart

**Comment by brunobat** [comment] 2021-03-15 10:51
This is still happening on com.newrelic.agent.java.newrelic-agent-5.12.0

**Comment by seancorfield** [comment] 2021-03-18 22:26
Still seeing this warning on the 6.4.2 version of the agent. Also, as of JDK 16: "OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release" (because we're currently using `--illegal-access=warn` to catch all such issues, knowing that a future JDK will not permit the reflective access at all).

Given that the release notes for 6.1.0 proudly proclaimed "The New Relic Java agent is now fully compatible with version 15 of the OpenJDK and Hotspot JDKs." I assume "compatibility" didn't include fixing this long-standing warning?

And as of JDK 16, we're now also seeing this warning: "OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended" (which I've seen reported against a few other tools as well).

**Comment by seancorfield** [comment] 2021-03-23 15:58
Note: Java 17 will deny this access completely so New Relic users will be prevented from moving to Java 17 until this is fixed: 

"As is possible in Java 9 through Java 16, it will no longer be possible to bypass strong encapsulation via the command-line option, --illegal-access." -- https://www.infoq.com/news/2021/03/java-news-roundup-mar15-2021/

**Comment by jasonjkeller** [comment] 2021-04-28 15:29
This will be addressed when we do the work to officially support Java 16. You can follow that issue here: https://github.com/newrelic/newrelic-java-agent/issues/215

Until then the "Illegal Reflective Access" is simply a warning and doesn't affect the agent functionality at all for Java 9 - 15.

**Comment by tineye89** [comment] 2021-09-03 15:38
@XiXiaPdx I turned logging up a bit but didn't see that "Invalid license key" error you referenced (see [log.txt](https://github.com/newrelic/newrelic-java-agent/files/7107005/log.txt))

**Comment by kford-newrelic** [comment] 2021-09-03 16:47
Illegal reflective access warnings being addressed as part of adding support for Java 16.

**Comment by jasonjkeller** [comment] 2021-09-03 17:13
@tineye89 I tested with `JVM runtime version 11.0.11+9-LTS-194` and it works just fine, no issues at all with the agent connecting and sending data. 

Your error looks to clearly be related to an invalid `license_key` given the `com.newrelic.agent.LicenseException` and not at all related to the `illegal reflective access operation` warnings that this issue is about. We don't have any control over how the Cloud Foundry buildpack bundles and configures the agent but they might be doing something weird with your license. I would verify that you've got a valid license for the correct account and if need be open a ticket with the support team for assistance.

**Comment by jasonjkeller** [comment] 2021-09-10 16:59
This has been addressed in the [PR to support Java 16](https://github.com/newrelic/newrelic-java-agent/pull/366) and will be released in the 7.3.0 version of the agent.

**Comment by seancorfield** [comment] 2021-09-17 06:18
@jasonjkeller Do you have an ETA for 7.3.0 at this point? And have you done any early testing with it against JDK 17 since that's GA now? Thanks.

**Comment by hpoettker** [comment] 2021-11-17 18:03
I'm using the release 7.4.0 with the the JDK
```
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)
```
and the warning is still there.

Is this a regression in 7.4.0? Or has the issue never been resolved?

**Comment by seancorfield** [comment] 2021-11-17 20:10
@hpoettker The only warning we see with 7.4.0 on JDK 17 is this:
```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
```
But I do recall seeing a _different_ reflection warning to the original one with 7.4.0 on JDK 11 which related to something in the JDK itself (if you try 7.3.0 and 7.4.0 on JDK 13, I believe you'll see the reflection warnings are different?).

**Comment by tbradellis** [comment] 2021-11-22 19:45
Reopened to do research on what log messages we expect to see across various JDK Versions given the changes in the agent to support JDK16+.

**Comment by hpoettker** [comment] 2021-12-01 19:43
@seancorfield Thanks for the quick reaction!

With JDK 13, I see the warning about Class Data Sharing and indeed a slightly different reflective access warning. It's produced by the same class but through accessing a different method;
```
WARNING: Illegal reflective access by
com.newrelic.weave.weavepackage.NewClassAppender (file:/opt/newrelic/newrelic.jar)
to method java.net.URLClassLoader.addURL(java.net.URL)
```

When the same application runs on
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)
```
it does indeed only produce the warning about CDS, which can be taken care of with `-Xshare:off`.

**Comment by tbradellis** [comment] 2022-01-14 01:25
Doing some final remarks here before closing out. 
The warning message below comes from the Class Data Sharing (CDS) or AppClass Data Sharing feature of the JDK:

`OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended`

This happens when something gets appended to the bootstrap classpath. The Java Agent does append to the bootstrap classpath. Essentially, it invalidates part of the Class Data archive, i.e. some part of the bootstrap portion.  I'm no CDS expert, but from what I can tell classes loaded by the system class loader would still be valid in the archive.  So, presumably JVMs making use of CDS could still benefit from that portion of the archive.
With CDS options there are ways to confirm which classes are still being shared with `-Xlog:class+load:file=<userdefinedlogname>`

This is all really beyond the scope of the question, but I mention it to point out that the log warning is benign and setting `-Xshare:off` may have unintended consequences if CDS is in use. But, if it's not being used, then certainly setting it to off will work to resolve the additional logging as indicated in the above comments.  The warning should only show up once at startup.
for reference:
http://openjdk.java.net/jeps/310
http://openjdk.java.net/jeps/341

CDS may not be expected to work with Java Agents to begin with (or maybe the dump file just can't be created when an agent is in use).  As implied here:
https://bugs.openjdk.java.net/browse/JDK-8201375
This is an interesting topic and I think deserves some further investigation, which we may take up in a separate issue.

For the purpose of this reported issue:
The various warning messages we see for different Java Agent versions and JDK versions are expected behavior.   Closing

**Closed by tbradellis** 2022-01-14 01:25 UTC
Labels: bug

**Comment by RomanVlasenko** [comment] 2023-05-15 13:19
Having the aforementioned warnings in place - is it safe to switch JVM option `--illegal-access` to `deny` mode on Java 11?
