### ISSUE TITLE
Negative Values Reported Deriving from StatsImpl and RepsponseTimeStatsImpl

### ISSUE THREAD

**Issue by tbradellis** [newrelic/newrelic-java-agent#709] opened 2022-02-17 23:44 UTC
A pernicious issue that has alluded root cause discovery for some time due to an inability to consistently reproduce it and/or obtain live logging data has finally been reproduced.
Internally, we have information here:
https://newrelic.atlassian.net/browse/GTSE-13353

It looks like in StatsImpl and RepsonseTimeStatsImpl we need to synchronize on a few metric aggregation points. 

https://github.com/newrelic/newrelic-java-agent/blob/6be021f3f3dc8e8f992ca8eba4ba070c03e1dd3c/newrelic-agent/src/main/java/com/newrelic/agent/stats/ResponseTimeStatsImpl.java#L67

https://github.com/newrelic/newrelic-java-agent/blob/6be021f3f3dc8e8f992ca8eba4ba070c03e1dd3c/newrelic-agent/src/main/java/com/newrelic/agent/stats/ResponseTimeStatsImpl.java#L128

https://github.com/newrelic/newrelic-java-agent/blob/6be021f3f3dc8e8f992ca8eba4ba070c03e1dd3c/newrelic-agent/src/main/java/com/newrelic/agent/stats/StatsImpl.java#L57

https://github.com/newrelic/newrelic-java-agent/blob/6be021f3f3dc8e8f992ca8eba4ba070c03e1dd3c/newrelic-agent/src/main/java/com/newrelic/agent/stats/StatsImpl.java#L123

The links here should not be considered an exhaustive description of where all the problem exists.  Addition metric debug information is provided in the logs from the reporting customers application, so we should double check that there aren't other places that show the Supportability metric for negative values.  We should check to see if the DefaultTracer had any hits in those logs.

## Additional context
[[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )](https://newrelic.atlassian.net/browse/GTSE-13353
)

**Comment by kford-newrelic** [comment] 2022-03-17 21:09
Bumped from the `7.6.0` release; will target for the next release.

**Comment by kford-newrelic** [comment] 2022-04-26 00:29
Not able to determine root cause after extensive exploration. Deferring this issue as a potential future roadmap consideration. Moving back to `Triage`.

**Comment by kford-newrelic** [comment] 2022-06-14 21:27
Was not able to include in FY23Q1's agent release. Not selected for next quarter's agent roadmap. Will consider for a future agent release.

**Comment by kford-newrelic** [comment] 2022-09-19 23:19
Not selected for the agent roadmap. Issue does not appear to be widespread/common.

**Comment by kford-newrelic** [comment] 2024-02-06 16:05
Issue appears to have resolved with #1685

**Closed by kford-newrelic** 2024-02-06 16:05 UTC
Labels: bug, GTSE
