### ISSUE TITLE
Java 17 reflective calls issue with CompletableFuture

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#526] opened 2021-10-29 14:14 UTC
## Description
A problem has been identified with reflective method calls into CompletableFuture from the agent in Java 17.

GTSE ticker here for details -> https://newrelic.atlassian.net/browse/GTSE-12065

**Comment by meiao** [comment] 2021-11-01 18:39
We used the following app (provided by the customer who opened the bug) to reproduce the error.
```
public class Tester {

    public static void main(String... args) throws Exception {
        Type type = Tester.class.getDeclaredMethod("testing").getGenericReturnType();
        System.out.println("TYPE: " + type);
    }

    public CompletableFuture<List<String>> testing() { return null; }
}
```

When this application is run, an exception is thrown on line 301 of SignatureParser, in parseClassTypeSignature.
![image](https://user-images.githubusercontent.com/292463/139721662-a9c5bb11-0935-4776-b751-33ad5d2ee862.png)

Adding a conditional breakpoint at the highlighted line in `SignatureParser#parseClassTypeSignature` (screenshot above) with the condition being `input.contains("Completable")` will make the execution stop 3 times there for the input `()Ljava/util/concurrent/CompletableFuture<Ljava/util/List<Ljava/lang/String;>;>;`. At this point, it is creating the `MethodRepository` for the `Tester#testing` method and the calls to the method `parseClassTypeSignature` are to parse the return type of the `Tester#testing` method.

Continuing with the execution, it will then stop at that breakpoint one more time. This time with input `java/util/concurrent/CompletableFuture`. At this point, it is trying to create a ParameterizedType based on CompletableFuture.

For some reason, `Class#getGenericSignature0()` (a native method) is returning the fore mentioned String, instead of the class signature which should be `<T:Ljava/lang/Object;>Ljava/lang/Object;Ljava/util/concurrent/Future<TT;>;Ljava/util/concurrent/CompletionStage<TT;>;`.

Comparing the bytecodes of the original CompletableFuture and the instrumented CompletableFuture, both have a line like
`Signature: #xyz  // <T:Ljava/lang/Object;>Ljava/lang/Object;Ljava/util/concurrent/Future<TT;>;Ljava/util/concurrent/CompletionStage<TT;>;`
where #xyz is a reference to the constants in the file.

This is the code in the JVM (ClassFileParser::parse_classfile_signature_attribute) that leads to believe that that line is what should be returned by getGenericSignature0 call.
![image](https://user-images.githubusercontent.com/292463/139723309-e6225b86-44ae-4f06-9d60-63dbe772c1e8.png)

**Comment by meiao** [comment] 2021-11-01 19:01
Changing the return type of `Tester#testing` to other instrumented classes, both with and without generics, will work as expected.

**Comment by meiao** [comment] 2021-11-08 16:11
A workaround is to disable CompletableFuture instrumentation by adding the following to the configuration file, under the `common` stanza:
```
  class_transformer:
    com.newrelic.instrumentation.java.completable-future-jdk8u40:
      enabled: false
```

**Comment by meiao** [comment] 2021-11-29 22:45
It has been reported that this can happen in other scenarios that do not involve the direct use of reflection.

For instance, a Spring bean that has a method that returns a CompletableFuture might trigger this error.

**Comment by meiao** [comment] 2021-12-06 16:05
Removing all code from the CompletableFuture instrumentation still reproduces the bug.
When this is done, we only add a couple of annotations to the class, but the following items are also modified:
- the order of items the Constant Pool, plus the new items due to the annotations
- method code has references updated to account for the changes in the Constant Pool
- a couple of methods have more drastic changes
- the StackMapTable gets bumped from the bottom of the Code of each method to above the LineNumberTable
- the class signature gets bumped down to below the Inner Classes

**Comment by mziemba** [comment] 2022-01-31 08:49
We've also encountered this issue, and sadly it's blocking us from migrating to Java 17

**Comment by meiao** [comment] 2022-02-17 00:11
We've created a [repository](https://github.com/meiao/genericSignature-jdk17-bug/) with a simple app that reproduces the issue and are investigation if this could possibly be a bug in the JDK.
Details on the investigation are being posted there for the time being.

**Comment by meiao** [comment] 2022-02-22 20:05
After investigating we believe this is a regressive bug in Java 17. We opened a bug with Oracle and they are investigating it.
https://bugs.openjdk.java.net/browse/JDK-8282241

**Comment by kford-newrelic** [comment] 2022-03-01 21:50
Bumped from `7.6.0` waiting for a fix to the JVM from Oracle. Will target for next available release.

**Comment by jasonjkeller** [comment] 2022-04-06 23:26
@rmatec @mziemba The "invalid generic signature" bug has been fixed in Java 19 by the OpenJDK folks but it is not clear if they intend to back-port the fix to Java 17 & 18: https://bugs.openjdk.java.net/browse/JDK-8282241

Unfortunately there's not much that can be done on New Relic's end regarding this as JVM bugs and fix back-ports are out of our control.

**Comment by hjain4** [comment] 2022-04-22 08:57
We faced this issue in our product and it was mitigated by the following statement:
  class_transformer:
    com.newrelic.instrumentation.java.completable-future-jdk8u40:
      enabled: false

Do we know what is impact of this in configured instrumentation.

**Comment by meiao** [comment] 2022-04-22 14:54
@hjain4, visibility on code that uses CompletableFuture will be lost from that point on.

So any libraries that rely on CompletableFuture will have decreased visibility.

**Comment by mattnelson** [comment] 2022-05-25 21:09
> Unfortunately there's not much that can be done on New Relic's end regarding this as JVM bugs and fix back-ports are out of our control.

Here is the backport request for 17.
https://bugs.openjdk.java.net/browse/JDK-8286566

**Closed as completed** 2022-10-19 14:42 UTC
Labels: bug, GTSE, blocked

**Comment by kibertoad** [comment] 2022-10-19 14:45
@dedePaulius I think this should unblock Elastum migration to 17, looks like 17.0.5 won't have compatibility issues with NewRelic anymore.

**Comment by meiao** [comment] 2024-07-22 13:42
For those who haven't updated their Java version but are using agent version 8.13.0 or newer, there is a new instrumentation module that must be disabled:
```
  class_transformer:
    com.newrelic.instrumentation.java.completable-future-jdk11:
      enabled: false
```
