### ISSUE TITLE
Exception cause is not shown in the logs for nested exceptions

### ISSUE THREAD

**Issue by iamFrancescoFerro** [newrelic/newrelic-java-agent#1189] opened 2023-03-22 12:13 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

When an exception is thrown, caught and then added to the cause for a new exception the original exception doesn't appear in the logs.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

For nested exception, the entire stack should be shown in the logs not just the first.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

Given you have something similar
```
public void test() {
  try {
      [..somelogic..]
      if (..) {
          throw new ACustomCheckedException("ERROR A");
      }
  } catch (Exception e) {
      throw new ACustomCheckedException("ERROR B", e);
  }
}

// someone calling that method
try {
    service.test();
} catch (Exception e) {
     log.error("ERROR C", e); 
}
```

The `log.error` normally prints a stack trace where at the bottom there is the original error

```
com.XXX.ACustomCheckedException: ERROR B
	at XXXXX [..... stacktrace....]
Caused by: com.XXXXX.ACustomCheckedException: ERROR A
	at XXXXXX
	... 91 common frames omitted
```

The `Caused by` is missing in the Newlic APM logs

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software, JVM vendor and version, framework versions, and any relevant configuration. )

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by kford-newrelic** [comment] 2023-04-20 20:59
@iamFrancescoFerro thank you for letting us know about this behavior - we are reviewing internally

**Comment by kford-newrelic** [comment] 2023-04-26 15:08
@iamFrancescoFerro our Team has reviewed this and while they've agreed that it worth pulling into our backlog, we consider it an enhancement not a bug. We cannot commit to a date when we would work this issue but as we plan our work for future quarters, we will consider this. Thank you for the suggestion!

**Comment by kford-newrelic** [comment] 2024-03-08 12:09
@iamFrancescoFerro apologies but we've decided _not_ to add this to our team's agent roadmap. However, if you feel motivated to write the code for this yourself, a PR submission would be welcome.

**Comment by jasonjkeller** [comment] 2024-04-05 18:58
The same logic has already been fixed in the log extensions so we can probably just port that over to the agent in each of the log framework instrumentation modules. https://github.com/newrelic/java-log-extensions/issues/54

**Closed** 2024-04-17 16:59 UTC
Labels: enhancement, GTSE, 2, apr-jun qtr
