### ISSUE TITLE
Failure when running on IBM Semeru Java 17

### ISSUE THREAD

**Issue by bogdanbrindusan** [newrelic/newrelic-java-agent#891] opened 2022-06-23 15:50 UTC
NR Java agent doesn't start on IBM Semeru Java 17, Certified Edition. 
Builds available here: https://developer.ibm.com/languages/java/semeru-runtimes/downloads/

It's basically the OpenJ9, which has been moved from Adoptopenjdk and renamed.

NR Java agent compatibility doesn't list support for Semeru Java 17, but I've been instructed by our NR account manager to log a ticket here.

## Description
When starting the Java app with latest NR Java agent (7.8.0) attached to Semeru Java 17 it crashes.

Stacktrace:
```
2022-06-23T15:43:45,650+0000 [1 1] com.newrelic INFO: New Relic Agent: Loading configuration file "/app/./newrelic.yml"
2022-06-23T15:43:46,372+0000 [1 1] com.newrelic INFO: Using default collector host: collector.newrelic.com
2022-06-23T15:43:46,372+0000 [1 1] com.newrelic INFO: Using default metric ingest URI: https://metric-api.newrelic.com/metric/v1
2022-06-23T15:43:46,373+0000 [1 1] com.newrelic INFO: Using default event ingest URI: https://insights-collector.newrelic.com/v1/accounts/events
2022-06-23T15:43:46,386+0000 [1 1] com.newrelic ERROR: Unable to start the New Relic Agent. Your application will continue to run but it will not be monitored.
java.lang.NoClassDefFoundError: com.newrelic.agent.bridge.datastore.RecordSql
        at com.newrelic.agent.config.TransactionTracerConfigImpl.<init>(TransactionTracerConfigImpl.java:97) ~[newrelic.jar:7.8.0]
        at com.newrelic.agent.config.TransactionTracerConfigImpl.createTransactionTracerConfigImpl(TransactionTracerConfigImpl.java:352) ~[newrelic.jar:7.8.0]
        at com.newrelic.agent.config.TransactionTracerConfigImpl.createTransactionTracerConfig(TransactionTracerConfigImpl.java:345) ~[newrelic.jar:7.8.0]
        at com.newrelic.agent.config.AgentConfigImpl.initTransactionTracerConfig(AgentConfigImpl.java:700) ~[newrelic.jar:7.8.0]
        at com.newrelic.agent.config.AgentConfigImpl.<init>(AgentConfigImpl.java:336) ~[newrelic.jar:7.8.0]
        at com.newrelic.agent.config.AgentConfigImpl.createAgentConfig(AgentConfigImpl.java:283) ~[newrelic.jar:7.8.0]
        at com.newrelic.agent.config.ConfigServiceFactory.createConfigService(ConfigServiceFactory.java:38) ~[newrelic.jar:7.8.0]
        at com.newrelic.agent.Agent.tryToInitializeServiceManager(Agent.java:199) [newrelic.jar:7.8.0]
        at com.newrelic.agent.Agent.continuePremain(Agent.java:140) [newrelic.jar:7.8.0]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at com.newrelic.bootstrap.BootstrapAgent.startAgent(BootstrapAgent.java:193) [newrelic.jar:7.8.0]
        at com.newrelic.bootstrap.BootstrapAgent.premain(BootstrapAgent.java:130) [newrelic.jar:7.8.0]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source) [?:?]
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: com.newrelic.agent.bridge.datastore.RecordSql
        at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 21 more
```

**Comment by kford-newrelic** [comment] 2022-06-23 19:43
@bogdanbrindusan thanks for the extra detail you provided on this issue. We're going to close this out as a dupe of #841 . We're not sure we can get to this in the Jul-Sep quarter's work but if not, we'll consider for a future quarter.

**Closed by kford-newrelic** 2022-06-23 19:43 UTC
Labels: bug
