### ISSUE TITLE
Spring Data Redis

### ISSUE THREAD

**Issue by tspring** [newrelic/newrelic-java-agent#199] opened 2021-01-26 17:14 UTC
Instrumentation for [reactive lettuce](https://github.com/lettuce-io/lettuce-core/wiki/Reactive-API-%285.0%29)

**Comment by XiXiaPdx** [comment] 2021-01-26 19:19
Start point to understand the api and samples 
https://spring.io/projects/spring-data-redis

**Comment by kford-newrelic** [comment] 2022-01-13 23:58
May ultimately be covered by #317

**Comment by kford-newrelic** [comment] 2022-02-28 23:18
Duplicate of #317 - closing

**Closed by kford-newrelic** 2022-02-28 23:18 UTC
Labels: enhancement, Spring Reactive DB, 7.6.0
