### ISSUE TITLE
Support Spring MVC functional controller

### ISSUE THREAD

**Issue by haupv1m** [newrelic/newrelic-java-agent#273] opened 2021-04-13 06:42 UTC
## Feature Description
From Spring 5.2, functional endpoint approach is already available on Spring MVC. However, currently, newrelic-java agent only support Spring MVC annotation controller

https://docs.spring.io/spring-framework/reference/web/webmvc-functional.html

## Describe Alternatives
Support Spring MVC HandlerFunction as Web request handler

(Migrate to Jira)

**Comment by jtduffy** [comment] 2023-12-13 12:18
This is a duplicate of #1576

**Comment by jtduffy** [comment] 2023-12-13 12:40
The existing instrumentation supports this pattern of controllers with RouterFunctions and registered handlers: For example:

```java
public class Greeting2Router {
    @Bean
    public RouterFunction<ServerResponse> routeGet(Greeting2Handler greetingHandler) {
        return RouterFunctions
                .route(GET("/greet2").and(accept(MediaType.APPLICATION_JSON)), greetingHandler::hello);
    }
}


public class Greeting2Handler {
    public Mono<ServerResponse> hello(ServerRequest request) {
        return ServerResponse.ok().contentType(MediaType.APPLICATION_JSON)
                .body(BodyInserters.fromValue(new Greeting("hello", "world")));
    }
}
```

**Closed by jtduffy** 2023-12-13 12:40 UTC
Labels: enhancement
