### ISSUE TITLE
Spring Reactive DB Drivers - MongoDB Support

### ISSUE THREAD

**Issue by tspring** [newrelic/newrelic-java-agent#198] opened 2021-01-26 17:08 UTC
Add out-of-the-box Java agent support for MongoDB under the Spring Reactive framework

See MMF [doc](https://docs.google.com/document/d/1wrM0B9puN0YR3Wn9jGbNrCu-fw63Di856wh3hlwhYF0/edit?usp=sharing)

Add support for Reactive calls for MongoDB so that database interactions are instrumented by the Java Agent.

MongoDB, Redis, and Cassandra all have native reactive support in [Spring Data](https://spring.io/projects/spring-data). Many relational databases (Postgres, Microsoft SQL Server, MySQL, H2, and Google Spanner) have reactive support via [R2DBC](https://github.com/r2dbc).

Confirm support for async.client.MongoClient

Particularly Mongo will report incorrect metrics for Async which has been an issue for a while.

Review [https://github.com/topics/nrlabs](https://github.com/topics/nrlabs) instrumentation for Mongo async, Lettuce, etc.

Aha! Link: https://newrelic.aha.io/features/JAVA-295

Write instrumentation and instrumentation tests for [MongoDB reactive streams](https://mongodb.github.io/mongo-java-driver/).

**Comment by jasonjkeller** [comment] 2021-06-21 17:50
The existing mongo instrumentation seems to be partially applying when mongo reactive is being used. This is causing a number of issues (skewed response times, memory pressure) as those instrumentation modules aren't intended to support mongo reactive. See this internal [slack thread](https://newrelic.slack.com/archives/G96BPDE4Q/p1623360414414400) for some additional context.

To prevent such issues when using mongo reactive the existing instrumentation should be disabled.

```
  class_transformer:
    com.newrelic.instrumentation.mongo-3.7:
      enabled: false
    com.newrelic.instrumentation.mongo-3.1:
      enabled: false
    com.newrelic.instrumentation.mongo-3.0:
      enabled: false
```

As part of the work to officially support mongo reactive we need to determine whether or not the old instrument should apply and be supplemented by an additional instrumentation specific to mongo reactive. Or we need to ensure that the old instrumentation modules don't apply at all and only the new mongo reactive instrumentation does.

**Comment by Stephan202** [comment] 2021-07-08 09:28
@jasonjkeller the instrumentation artifact IDs use `mongodb` rather than `mongo`. Updating your suggestion accordingly, I can confirm that the following works:
```
  class_transformer:
    com.newrelic.instrumentation.mongodb-3.7:
      enabled: false
    com.newrelic.instrumentation.mongodb-3.1:
      enabled: false
    com.newrelic.instrumentation.mongodb-3.0:
      enabled: false
```

Any update on reactive driver support? The vast majority of our MongoDB integrations us the reactive driver, and we're pretty blind at the moment. To be honest, it's a pretty big issue :(

**Comment by Stephan202** [comment] 2021-07-08 10:25
We have a number of applications that use both the sync and async driver. When using a version 3.x MongoDB driver we could see the synchronous queries, while the asynchronous queries did not show up in New Relic. Now that we have upgraded to driver version 4.x we hit the transaction timeout issue discussed above. This forces us to disable instrumentation of the synchronous driver as suggested, thus further reducing our visibility.

I see that version 4.0.0 of the MongoDB driver landed in Maven Central on 2020-03-04, i.e. 16 months ago. Given MongoDB's popularity, can you please prioritize support for the 4.x line? As a customer, is there anything we can do to help?

**Comment by Stephan202** [comment] 2021-07-08 16:41
Upon further testing we concluded that disabling _just_ the MongoDB 3.7 instrumentation is enough:
```
  class_transformer:
    com.newrelic.instrumentation.mongodb-3.7:
      enabled: false
```

This way new Relic still reports queries by the synchronous driver, thereby maintaining the status quo. (Apparently the fallback to the 3.1 or 3.0 instrumentation suffices.)

@nathankooij filed a PR that is expected to restore this behavior out of the box: #341.

**Comment by jasonjkeller** [comment] 2021-10-21 22:22
SpringBoot 2.0.x introduced two different async drivers for mongdb.
- `org.mongodb:mongodb-driver-async`
- `org.mongodb:mongodb-driver-reactivestreams`

SpringBoot [2.0.x](https://github.com/spring-projects/spring-boot/blob/2.0.x/spring-boot-project/spring-boot-dependencies/pom.xml#L2450-L2479)
```
org.mongodb:mongodb-driver-async:3.6.4
org.mongodb:mongodb-driver-reactivestreams:1.7.1
```

SpringBoot [2.1.x](https://github.com/spring-projects/spring-boot/blob/2.1.x/spring-boot-project/spring-boot-dependencies/pom.xml#L2422-L2451)
```
org.mongodb:mongodb-driver-async:3.8.2
org.mongodb:mongodb-driver-reactivestreams:1.9.2
```

SpringBoot [2.2.x](https://github.com/spring-projects/spring-boot/blob/2.2.x/spring-boot-project/spring-boot-dependencies/pom.xml#L2662-L2691)
```
org.mongodb:mongodb-driver-async:3.11.2
org.mongodb:mongodb-driver-reactivestreams:1.12.0
```

---

The `org.mongodb:mongodb-driver-async` driver was removed as of SpringBoot 2.3.x.

SpringBoot [2.3.x](https://github.com/spring-projects/spring-boot/blob/2.3.x/spring-boot-project/spring-boot-dependencies/build.gradle#L1200-L1210)
```
org.mongodb:mongodb-driver-reactivestreams:4.0.6
```

SpringBoot [2.4.x](https://github.com/spring-projects/spring-boot/blob/2.4.x/spring-boot-project/spring-boot-dependencies/build.gradle#L1150-L1160)
```
org.mongodb:mongodb-driver-reactivestreams:4.1.2
```

SpringBoot [2.5.x](https://github.com/spring-projects/spring-boot/blob/2.5.x/spring-boot-project/spring-boot-dependencies/build.gradle#L1238-L1248)
```
org.mongodb:mongodb-driver-reactivestreams:4.2.3
```

**Closed** 2022-01-07 23:50 UTC
Labels: enhancement, Spring Reactive DB, 7.5.0
