### ISSUE TITLE
gRPC server instrumentation can not link grpc request transaction

### ISSUE THREAD

**Issue by mashiro** [newrelic/newrelic-java-agent#942] opened 2022-07-21 05:44 UTC
## Description
When gRPC instrumentation is used, the token is not active in the server method and cannot be linked by asynchronous operation.
Also, if `@Trace(dispatcher = true)` is given in the server method, subsequent segments of asynchronous operations will not be recorded as transactions.
This will work correctly if grpc-instrumentation is disabled.

## Expected Behavior
token is active in gRPC server method.

## Your Environment
* gRPC 1.47.0
* NewRelic Agent 7.8.0

(Migrate to Jira)

**Comment by kford-newrelic** [comment] 2022-08-01 14:58
@mashiro thanks for letting us know about this issue

Any chance you have a sample app/code that reproduces this issue?

**Comment by mashiro** [comment] 2022-08-02 05:35
Hi, @kford-newrelic 
I use grpc-java example code. https://grpc.io/docs/languages/java/quickstart/#get-the-example-code

1. Implement debug code to HelloWorldServer.java
```
Token token = NewRelic.getAgent().getTransaction().getToken();
System.out.println("token.isActive() = " + token.isActive());
```
2. Download newrelic agent to example directory
3. Run hello-world-server with newrelic-agent
```
HELLO_WORLD_SERVER_OPTS="-javaagent:../../../../newrelic/newrelic.jar" ./hello-world-server
```
4. Run hello-world-client
```
./hello-world-client
```

**Comment by kford-newrelic** [comment] 2022-11-30 00:16
Targeted for the Jan-Mar quarter

**Comment by obenkenobi** [comment] 2023-01-06 19:28
The bug is already fixed for the upcoming 8.0 release so I am closing off the issue.

**Closed** 2023-01-06 19:29 UTC
Labels: Q4 SC, on-roadmap

**Comment by obenkenobi** [comment] 2023-01-06 19:51
For reference, this issue is a duplicate of [another issue](https://github.com/newrelic/newrelic-java-agent/issues/1023) which already closed out.
