### ISSUE TITLE
Slow SQL traces not received in the expected section from New Relic Java agent

### ISSUE THREAD

**Issue by devleifr** [newrelic/newrelic-java-agent#1937] opened 2024-06-11 14:13 UTC
## Description

I'm experiencing an issue with the New Relic Java agent where Slow SQL traces are not shown in the New Relic dashboard. I can see these SQL-connected traces under **Monitor > Transactions** and they are categorized under the `.other` segment. 

Additionally, I did not find any enable/disable option for Slow SQL traces like those available in [other language agents](https://docs.newrelic.com/docs/apm/apm-ui-pages/monitoring/view-slow-query-details/#go).

## Expected Behavior
Slow SQL traces should appear in the New Relic dashboard under the Monitor > Databases > Slow SQL traces section.

## Troubleshooting

The **Slow SQL** traces section is empty:
![Screenshot from 2024-06-11 16-31-30](https://github.com/newrelic/node-newrelic/assets/21125397/49a6c7cb-728e-4135-8f2a-ba068cd7602e)

SQL-connected traces under **Monitor > Transactions**: 

![Screenshot from 2024-06-11 17-18-42](https://github.com/newrelic/newrelic-java-agent/assets/21125397/1f43946c-2b60-46f0-8d8f-8bcf866cc0a2)

![Screenshot from 2024-06-11 17-18-08](https://github.com/newrelic/newrelic-java-agent/assets/21125397/859f10ba-2e60-4b50-8e6c-a0ade72022de)

![Screenshot from 2024-06-11 16-54-28](https://github.com/newrelic/node-newrelic/assets/21125397/238e230e-4cff-456b-953c-7e73466c8a64)

![Screenshot from 2024-06-11 17-17-16](https://github.com/newrelic/newrelic-java-agent/assets/21125397/d8578bff-e0a7-4e99-8a91-1200646d6e1f)  
![Screenshot from 2024-06-11 17-17-27](https://github.com/newrelic/newrelic-java-agent/assets/21125397/01a26bb8-710a-45fb-8831-ad2ac4b7b0f0)

## Steps to Reproduce

Specify your license key under the `NEW_RELIC_LICENSE_KEY` variable in `docker-compose.yml`.
Then run `docker compose up --build`.

[java_nr_sql_repro.zip](https://github.com/user-attachments/files/15789249/java_nr_sql_repro.zip)

## Environment Details:

- Java version: 16
- New Relic agent version: 8.12.0
- PostgreSQL driver version: 42.7.3
- PostgreSQL: 13.1

**Comment by jbedell-newrelic** [comment] 2024-07-18 18:44
Hi @devleifr,

So far I've been unable to reproduce this issue.  My slow SQL queries are showing up in the expected UI page.  Can you share a little more information about your setup?

**Comment by devleifr** [comment] 2024-07-19 07:26
> Hi @devleifr,
> 
> So far I've been unable to reproduce this issue. My slow SQL queries are showing up in the expected UI page. Can you share a little more information about your setup?

Hi @jbedell-newrelic! Have you tried the `[reproduction spring application](https://github.com/user-attachments/files/15789249/java_nr_sql_repro.zip)` that I provided in "Steps to reproduce"?

**Comment by jbedell-newrelic** [comment] 2024-07-19 12:12
@devleifr I'm sorry to say I somehow completely missed that.  Thanks for the reminder.

**Comment by jbedell-newrelic** [comment] 2024-07-19 20:41
Hi @devleifr It looks like your repro app does a simple `select pg_sleep()` call.  We refer to this as a [select VARIABLE](https://github.com/newrelic/newrelic-java-agent/blob/1a93e4a4c2c4c06a353306615e099c426c9c8efb/newrelic-agent/src/main/java/com/newrelic/agent/database/SelectVariableStatementFactory.java#L16) call, and that type of call is never going to report a metric up.  

Is that representative of the problem query in your actual application? 

If so and would like it to show up, you may try to append an arbitrary `from <table_name>` to the query, which should parse differently and should produce a metric being sent up.

**Comment by jbedell-newrelic** [comment] 2024-07-29 13:19
Going to be closing this issue.  If you need to re-open it, please feel free.

**Closed by jbedell-newrelic** 2024-07-29 13:19 UTC
Labels: bug, 2, jul-sep qtr
